var NAVTREEINDEX0 =
{
"@ref curated_io_api":[1],
"@ref curated_io_api_attributes":[1,2],
"@ref curated_io_api_dataset":[1,1],
"@ref curated_io_api_file":[1,0],
"@ref curated_io_api_file_create":[1,0,0],
"@ref curated_io_api_file_open":[1,0,1],
"@ref curated_io_api_groups":[1,3],
"@ref curated_topics":[2],
"@ref curated_topics_cdash":[2,8],
"@ref curated_topics_error":[2,6],
"@ref curated_topics_filters":[2,4],
"@ref curated_topics_linalg":[2,1],
"@ref curated_topics_mpi":[2,5],
"@ref curated_topics_properties":[2,0],
"@ref curated_topics_reflection":[2,3],
"@ref curated_topics_stl":[2,2],
"@ref curated_topics_typesystem":[2,7],
"@ref example_guide_attributes":[3,2],
"@ref example_guide_basics":[3,0],
"@ref example_guide_compound":[3,5],
"@ref example_guide_container":[3,6],
"@ref example_guide_cout":[3,18],
"@ref example_guide_csv":[3,25],
"@ref example_guide_custom_pipeline":[3,17],
"@ref example_guide_datasets":[3,1],
"@ref example_guide_datatypes":[3,4],
"@ref example_guide_groups":[3,3],
"@ref example_guide_half_float":[3,24],
"@ref example_guide_linalg":[3,10],
"@ref example_guide_mdspan":[3,12],
"@ref example_guide_mpi":[3,27],
"@ref example_guide_multi_tu":[3,23],
"@ref example_guide_optimized":[3,14],
"@ref example_guide_packet_table":[3,16],
"@ref example_guide_pprint":[3,19],
"@ref example_guide_raw_memory":[3,15],
"@ref example_guide_reference":[3,20],
"@ref example_guide_reflection":[3,22],
"@ref example_guide_s3":[3,26],
"@ref example_guide_smart_ptr":[3,21],
"@ref example_guide_sparse":[3,11],
"@ref example_guide_stl":[3,7],
"@ref example_guide_string":[3,8],
"@ref example_guide_transform":[3,13],
"@ref example_guide_utf":[3,9],
"@ref examples_guides_index":[3],
"@ref reports_index":[5],
"@ref reports_usability_evaluation":[4],
"index.html":[0],
"index.html":[],
"pages.html":[]
};
