#!/usr/bin/env python3
# Copyright (c) 2026 Steven Varga, Toronto, ON, Canada
# MIT License — see LICENSE
"""
Amalgamate the plot headers into a single self-contained plot.hpp.

Usage:
    python3 scripts/amalgamate.py <include/plot dir> <output-file>

Example:
    python3 scripts/amalgamate.py include/plot build/plot.hpp

The include order is read from the `all` umbrella header (the canonical,
dependency-correct order). Each listed header is inlined with its internal
quoted includes ("foo.hpp") and `#pragma once` stripped; system includes
(<vector>, …) are kept (they are idempotent under their own guards). Per-file
`#ifndef` guards are kept — harmless, and they keep each block self-describing.
The whole thing is wrapped in one PLOT_HPP guard.
"""

import re
import sys
from pathlib import Path

QUOTED_INCLUDE = re.compile(r'^\s*#\s*include\s+"[^"]+"')


def ordered_headers(plot_dir: Path) -> list[str]:
    """Return the header filenames in `all`-umbrella order."""
    all_file = plot_dir / "all"
    if not all_file.exists():
        sys.exit(f"Error: umbrella header {all_file} not found.")
    names = []
    for line in all_file.read_text(encoding="utf-8").splitlines():
        m = re.match(r'\s*#\s*include\s+"([^"]+)"', line)
        if m:
            names.append(m.group(1))
    return names


def process(filepath: Path) -> str:
    """Strip `#pragma once` and internal quoted includes from a header."""
    out = []
    for line in filepath.read_text(encoding="utf-8").splitlines():
        if line.strip() == "#pragma once":
            continue
        if QUOTED_INCLUDE.match(line):
            continue
        out.append(line)
    return "\n".join(out)


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    plot_dir = Path(sys.argv[1])
    output = Path(sys.argv[2])

    headers = ordered_headers(plot_dir)

    parts = [
        "/*",
        " * plot — single-header amalgamated distribution.",
        " * Header-only, dependency-free C++ SVG plotting library.",
        " * Copyright (c) 2026 Steven Varga — MIT License.",
        " *",
        " * Generated by scripts/amalgamate.py — do not edit by hand.",
        " */",
        "#ifndef PLOT_HPP",
        "#define PLOT_HPP",
        "",
    ]

    count = 0
    for name in headers:
        fp = plot_dir / name
        if not fp.exists():
            print(f"Warning: {fp} not found, skipping.")
            continue
        parts.append(f"/* ===== plot/{name} ===== */")
        parts.append(process(fp))
        parts.append("")
        count += 1

    parts.append("#endif /* PLOT_HPP */")
    parts.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(parts), encoding="utf-8")
    print(f"Generated {output} ({count} headers amalgamated)")


if __name__ == "__main__":
    main()
